language: node_js

sudo: false

node_js:
  - "10"
  - "12"

install:
  - yarn --frozen-lockfile

script:
  - node --version
  - yarn run build
  - yarn run lint
  - yarn run test

cache: yarn

branches:
  only:
    - master