name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Installing
        run: yarn install --frozen-lockfile
      - name: Linting
        run: yarn lint
      - name: Testing
        run: yarn test
      - name: Build
        run: yarn build
